#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tempest
Version  : 19.0.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/fb/c7/43a6b75c69bc620299e18391dc752c7bb9b0db77ca0b76235e2d506362ea/tempest-19.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/fb/c7/43a6b75c69bc620299e18391dc752c7bb9b0db77ca0b76235e2d506362ea/tempest-19.0.0.tar.gz
Summary  : TEMPest is \a CLI tool to help manage temporary content - writtent in go
Group    : Development/Tools
License  : Apache-2.0
Requires: tempest-bin = %{version}-%{release}
Requires: tempest-config = %{version}-%{release}
Requires: tempest-license = %{version}-%{release}
Requires: tempest-python = %{version}-%{release}
Requires: tempest-python3 = %{version}-%{release}
Requires: PyYAML
Requires: cliff
Requires: debtcollector
Requires: fixtures
Requires: jsonschema
Requires: netaddr
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.log
Requires: oslo.serialization
Requires: oslo.utils
Requires: paramiko
Requires: pbr
Requires: python-subunit
Requires: six
Requires: stestr
Requires: stevedore
Requires: testtools
Requires: unittest2
Requires: urllib3
BuildRequires : PyYAML
BuildRequires : buildreq-distutils3
BuildRequires : cliff
BuildRequires : coverage-python
BuildRequires : debtcollector
BuildRequires : fixtures
BuildRequires : flake8-import-order-python
BuildRequires : hacking
BuildRequires : jsonschema
BuildRequires : netaddr
BuildRequires : oslo.concurrency
BuildRequires : oslo.config
BuildRequires : oslo.log
BuildRequires : oslo.serialization
BuildRequires : oslo.utils
BuildRequires : oslotest
BuildRequires : oslotest-python
BuildRequires : paramiko
BuildRequires : pbr
BuildRequires : pluggy
BuildRequires : prettytable
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-subunit
BuildRequires : six
BuildRequires : stestr
BuildRequires : stevedore
BuildRequires : testtools
BuildRequires : tox
BuildRequires : unittest2
BuildRequires : urllib3
BuildRequires : virtualenv
Patch1: deps.patch

%description
Setup Tempest run folder.
To support isolation between multiple runs, separate run folders are required.
Set `tempest` as owner of Tempest's current run folder.
There is an implicit assumption here of a one to one relationship between
devstack versions and Tempest runs.

%package bin
Summary: bin components for the tempest package.
Group: Binaries
Requires: tempest-config = %{version}-%{release}
Requires: tempest-license = %{version}-%{release}

%description bin
bin components for the tempest package.


%package config
Summary: config components for the tempest package.
Group: Default

%description config
config components for the tempest package.


%package license
Summary: license components for the tempest package.
Group: Default

%description license
license components for the tempest package.


%package python
Summary: python components for the tempest package.
Group: Default
Requires: tempest-python3 = %{version}-%{release}

%description python
python components for the tempest package.


%package python3
Summary: python3 components for the tempest package.
Group: Default
Requires: python3-core

%description python3
python3 components for the tempest package.


%prep
%setup -q -n tempest-19.0.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559833509
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tempest
cp LICENSE %{buildroot}/usr/share/package-licenses/tempest/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/check-uuid
/usr/bin/skip-tracker
/usr/bin/subunit-describe-calls
/usr/bin/tempest
/usr/bin/tempest-account-generator
/usr/bin/verify-tempest-config

%files config
%defattr(-,root,root,-)
%config /usr/etc/tempest/accounts.yaml.sample
%config /usr/etc/tempest/logging.conf.sample
%config /usr/etc/tempest/whitelist.yaml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tempest/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
